#include "token.h"

using namespace Lazy;

std::ostream &Lazy::operator<<(std::ostream &os, const TokenType &tokenType) {
    os << tokenTypeToString(tokenType);
    return os;
}

std::ostream &Lazy::operator<<(std::ostream &os, const Token &token) {
    os << token.type << " " << token.line << ":" << token.column << " len" << token.text.length() <<  " " << token.text;
    return os;
}

std::string_view Lazy::tokenTypeToString(const TokenType &tokenType) {
    switch (tokenType) {
        case TokenType::NUMBER_L: return "NumberL";
        case TokenType::DECIMAL_L: return "DecimalL";
        case TokenType::CHAR_L: return "CharL";
        case TokenType::STRING_L: return "StringL";
        case TokenType::TRUE_L: return "TrueL";
        case TokenType::FALSE_L: return "FalseL";
        case TokenType::NULL_L: return "NullL";
        case TokenType::IDENTIFIER: return "Identifier";
        case TokenType::IF: return "If";
        case TokenType::ELSE: return "Else";
        case TokenType::MATCH: return "Match";
        case TokenType::WHEN: return "When";
        case TokenType::DO: return "Do";
        case TokenType::WHILE: return "While";
        case TokenType::FOR: return "For";
        case TokenType::BREAK: return "Break";
        case TokenType::CONTINUE: return "Continue";
        case TokenType::IN: return "In";
        case TokenType::THIS: return "This";
        case TokenType::SUPER: return "Super";
        case TokenType::DATA: return "Data";
        case TokenType::CLASS: return "Class";
        case TokenType::OBJECT: return "Object";
        case TokenType::INTERFACE: return "Interface";
        case TokenType::ENUM: return "Enum";
        case TokenType::ANNOTATION: return "Annotation";
        case TokenType::STATIC: return "Static";
        case TokenType::OPEN: return "Open";
        case TokenType::ABSTRACT: return "Abstract";
        case TokenType::PERMITS: return "Permits";
        case TokenType::ASYNC: return "Async";
        case TokenType::AWAIT: return "Await";
        case TokenType::EXTERN: return "Extern";
        case TokenType::INLINE: return "Inline";
        case TokenType::FN: return "Fn";
        case TokenType::RETURN: return "Return";
        case TokenType::OVERRIDE: return "Override";
        case TokenType::YIELD: return "Yield";
        case TokenType::ARROW: return "Arrow";
        case TokenType::PUBLIC: return "Public";
        case TokenType::PROTECTED: return "Protected";
        case TokenType::SEALED: return "Sealed";
        case TokenType::PRIVATE: return "Private";
        case TokenType::NAMESPACE: return "Namespace";
        case TokenType::IMPORT: return "Import";
        case TokenType::FROM: return "From";
        case TokenType::AS: return "As";
        case TokenType::TRY: return "Try";
        case TokenType::CATCH: return "Catch";
        case TokenType::FINALLY: return "Finally";
        case TokenType::THROW: return "Throw";
        case TokenType::ASSERT: return "Assert";
        case TokenType::VAR: return "Var";
        case TokenType::VAL: return "Val";
        case TokenType::BOOLEAN: return "Boolean";
        case TokenType::CHAR: return "Char";
        case TokenType::STRING: return "String";
        case TokenType::BYTE: return "Byte";
        case TokenType::SHORT: return "Short";
        case TokenType::INT: return "Int";
        case TokenType::LONG: return "Long";
        case TokenType::FLOAT: return "Float";
        case TokenType::DOUBLE: return "Double";
        case TokenType::UNSIGNED: return "Unsigned";
        case TokenType::TRUE: return "True";
        case TokenType::FALSE: return "False";
        case TokenType::NULL_: return "Null";
        case TokenType::DELETE: return "Delete";
        case TokenType::TYPEALIAS: return "Typealias";
        case TokenType::EQUAL: return "Equal";
        case TokenType::DOUBLE_EQUAL: return "DoubleEqual";
        case TokenType::PLUS: return "Plus";
        case TokenType::PLUS_EQUAL: return "PlusEqual";
        case TokenType::DOUBLE_PLUS: return "DoublePlus";
        case TokenType::MINUS: return "Minus";
        case TokenType::MINUS_EQUAL: return "MinusEqual";
        case TokenType::DOUBLE_MINUS: return "DoubleMinus";
        case TokenType::STAR: return "Star";
        case TokenType::STAR_EQUAL: return "StarEqual";
        case TokenType::DOUBLE_STAR: return "DoubleStar";
        case TokenType::DOUBLE_STAR_EQUAL: return "DoubleStarEqual";
        case TokenType::SLASH: return "Slash";
        case TokenType::SLASH_EQUAL: return "SlashEqual";
        case TokenType::DOUBLE_SLASH: return "DoubleSlash";
        case TokenType::DOUBLE_SLASH_EQUAL: return "DoubleSlashEqual";
        case TokenType::PERCENT: return "Percent";
        case TokenType::PERCENT_EQUAL: return "PercentEqual";
        case TokenType::AT: return "At";
        case TokenType::AT_EQUAL: return "AtEqual";
        case TokenType::EXCLAMATION_MARK: return "ExclamationMark";
        case TokenType::EXCLAMATION_MARK_EQUAL: return "ExclamationMarkEqual";
        case TokenType::GREATER_THAN: return "GreaterThan";
        case TokenType::GREATER_THAN_EQUAL: return "GreaterThanEqual";
        case TokenType::DOUBLE_GREATER_THAN: return "DoubleGreaterThan";
        case TokenType::DOUBLE_GREATER_THAN_EQUAL: return "DoubleGreaterThanEqual";
        case TokenType::LESS_THAN: return "LessThan";
        case TokenType::LESS_THAN_EQUAL: return "LessThanEqual";
        case TokenType::DOUBLE_LESS_THAN: return "DoubleLessThan";
        case TokenType::DOUBLE_LESS_THAN_EQUAL: return "DoubleLessThanEqual";
        case TokenType::TRIPLE_GREATER_THAN: return "TripleGreaterThan";
        case TokenType::TRIPLE_GREATER_THAN_EQUAL: return "TripleGreaterThanEqual";
        case TokenType::TILDE: return "Tilde";
        case TokenType::TILDE_EQUAL: return "TildeEqual";
        case TokenType::AMPERSAND: return "Ampersand";
        case TokenType::AMPERSAND_EQUAL: return "AmpersandEqual";
        case TokenType::DOUBLE_AMPERSAND: return "DoubleAmpersand";
        case TokenType::PIPE: return "Pipe";
        case TokenType::PIPE_EQUAL: return "PipeEqual";
        case TokenType::DOUBLE_PIPE: return "DoublePipe";
        case TokenType::CARET: return "Caret";
        case TokenType::CARET_EQUAL: return "CaretEqual";
        case TokenType::DOT: return "Dot";
        case TokenType::COMMA: return "Comma";
        case TokenType::COLON: return "Colon";
        case TokenType::SEMICOLON: return "Semicolon";
        case TokenType::QUESTION_MARK: return "QuestionMark";
        case TokenType::EXCLAMATION_DOT: return "ExclamationDot";
        case TokenType::QUESTION_DOT: return "QuestionDot";
        case TokenType::QUESTION_COLON: return "QuestionColon";
        case TokenType::LEFT_PAREN: return "LeftParen";
        case TokenType::RIGHT_PAREN: return "RightParen";
        case TokenType::LEFT_BRACE: return "LeftBrace";
        case TokenType::RIGHT_BRACE: return "RightBrace";
        case TokenType::LEFT_BRACKET: return "LeftBracket";
        case TokenType::RIGHT_BRACKET: return "RightBracket";
        case TokenType::END_OF_FILE: return "EndOfFile";
        case TokenType::UNKNOWN: return "Unknown";
        case TokenType::ERROR: return "Error";
        case TokenType::BAD_TOKEN: return "BadToken";
        default: return "<UnknownTokenType>";
    }
}
